GET http://127.0.0.1:8000/api/contacts HTTP/1.1

###
POST http://127.0.0.1:8000/api/contact HTTP/1.1
Content-Type: application/json


{
    "name" : "kali",
    "email" : "kali@gmail.com",
    "telephone": "029281919118"
}

###
PUT http://127.0.0.1:8000/api/contact/2 HTTP/1.1
Content-Type: application/json

{
    "name" : "Benjdia OS",
    "email" : "OS@google.com",
    "telephone": "+212 92819111"
}

###
DELETE http://127.0.0.1:8000/api/contact/1 HTTP/1.1


//test for user

###
GET http://127.0.0.1:8000/api/users HTTP/1.1

###
POST http://127.0.0.1:8000/api/user HTTP/1.1
Content-Type: application/json

{
    "name" : "kali linux",
    "email" : "kalii@gmail.com",
    "password": "benjdia"
}

###
PUT http://127.0.0.1:8000/api/user/4 HTTP/1.1
Content-Type: application/json

{
    "name" : "GNU Linux",
    "email" : "OS@google.com",
    "password": "password"
}

###
DELETE http://127.0.0.1:8000/api/user/4 HTTP/1.1

//test for product
###
GET http://127.0.0.1:8000/api/products HTTP/1.1

###
POST http://127.0.0.1:8000/api/product HTTP/1.1
Content-Type: application/json

{
    "libelle" : "kali",
    "price" : 132,
    "previousprice": 334,
    "image" : "folder_1/subfolder_1/eb0574ef8c9fe7efca98371a8f213b97.png"
}

###
PUT http://127.0.0.1:8000/api/product/7 HTTP/1.1
Content-Type: application/json

{
    "libelle" : "kali_coffee",
    "price" : 132,
    "previousprice": 200,
    "image" : "1AAddddddddddd"
}

###
DELETE http://127.0.0.1:8000/api/product/7 HTTP/1.1